# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20160410_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanceWin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1Seed', models.IntegerField()),
                ('team2Seed', models.IntegerField()),
                ('gameRound', models.IntegerField()),
                ('winT1', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
