# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20160410_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='chancewin',
            name='team1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chancewin',
            name='team2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pastgame',
            name='team1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pastgame',
            name='team2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
