# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20160410_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chancewin',
            old_name='team1',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='chancewin',
            old_name='team1Seed',
            new_name='teamSeed',
        ),
        migrations.RenameField(
            model_name='chancewin',
            old_name='winT1',
            new_name='winPer',
        ),
        migrations.RenameField(
            model_name='pastgame',
            old_name='team1',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='pastgame',
            old_name='team1Seed',
            new_name='teamSeed',
        ),
        migrations.RemoveField(
            model_name='chancewin',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='chancewin',
            name='team2Seed',
        ),
        migrations.RemoveField(
            model_name='pastgame',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='pastgame',
            name='team2Seed',
        ),
    ]
