# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20160410_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chancewin',
            old_name='team',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='chancewin',
            old_name='winPer',
            new_name='winPer1',
        ),
        migrations.RemoveField(
            model_name='chancewin',
            name='teamSeed',
        ),
        migrations.AddField(
            model_name='chancewin',
            name='team1Seed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chancewin',
            name='team2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chancewin',
            name='team2Seed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chancewin',
            name='gameRound',
            field=models.IntegerField(default=0),
        ),
    ]
